### ISSUE TITLE
Register ChordalGraph v0.4.0

### ISSUE THREAD

**Issue by adrien-le-franc** [wangjie212/ChordalGraph#1]
Hi Jie,
thanks for the update from LightGraphs to Graphs ! Could you please register ChordalGraph v0.4.0 so that it can be directly added from REPL ? Currently I believe only v0.2.0 is accessible.

**Comment by wangjie212** [comment]
Hi Adrien,

I have checked at https://juliahub.com/ui/Registrator, and ChordalGraph v0.4.0 was already registered. I don't see why only v0.2.0 is accessible.

**Comment by adrien-le-franc** [comment]
Hi Jie,

thanks for checking, maybe I had conflicting versions of the package or maybe something changed since then : anyway I can confirm that the default added version is well v0.4.0 so I guess we can close this issue.
